### ISSUE TITLE
A list of forms that need mappings

### ISSUE THREAD

**Issue by esonderegger** [esonderegger/fecfile#1]
This is generated by `python tests.py AllFormsHaveMappings.test_request` with that test uncommented. These are the missing mappings found from the first 5000 .fec files. Eventually the goal is to get through all filings without raising any `FecParserMissingMappingError` exceptions.

- [x] version 2.02 of form F6A
- [x] version 2.02 of form F3PA
- [x] version 1.02 of form H1
- [x] version 2.02 of form F6N
- [x] version 2.02 of form F3PN
- [x] version 2.02 of form SF25
- [x] version 2.02 of form H4
- [x] version 2.02 of form H3
- [x] version 2.02 of form H2
- [x] version 2.02 of form H1

And a list of newer missing mapping:
- [x] version P3.4 of form F3PT
- [x] version 8.3 of form F3A
- [x] version 8.3 of form F99
- [x] version 8.3 of form F3T
- [x] version 8.3 of form F1N
- [x] version P3.4 of form F6N
- [x] version 8.3 of form F5N
- [x] version P3.4 of form F1N
- [x] version 8.3 of form F3XA
- [x] version 8.3 of form F3N
- [x] version 8.3 of form F1MN
- [x] version P3.4 of form F1A
- [x] version 8.3 of form F3XN
- [x] version 8.3 of form F6N
- [x] version 8.3 of form F3XT
- [x] version 8.3 of form F1A
- [x] version P3.4 of form F6A
- [x] version P3.4 of form F3XN
- [x] version 8.3 of form F6A
- [x] version 8.3 of form F24N
- [x] version 8.3 of form F24A
- [x] version P3.4 of form F3XA
- [x] version 8.3  of form F3XN
- [x] version P3.4 of form F1M

More forms to add to the list (9/28/2018: 1250000-1259000)
- [x] version P3.4 of form F1M
- [x] version P3.4 of form F1S
- [x] version P3.4 of form F2A
- [x] version P3.4 of form F2N
- [x] version P3.4 of form F3LN
- [x] version P3.4 of form F3S
- [x] version P3.4 of form F5A
- [x] version P3.4 of form F5N
- [x] version P3.4 of form F65
- [x] version P3.4 of form F7N
- [x] version P3.4 of form F9N
- [x] version P3.4 of form SC1
- [x] version P3.4 of form SC2/9
- [x] version P3.4 of form SE
- [x] version P3.4 of form SF
- [x] version P3.4 of form H1
- [x] version P3.4 of form H2
- [x] version P3.4 of form H4

**Comment by jsfenfen** [comment]
FWIW this is slightly longer than need be; in other words, if you've got a mapping for a v8.3 F3XA it'll work for F3XN too--you might wanna chop [A|N|T] from the last letter of the form type in generating this, I guess.

**Comment by esonderegger** [comment]
yeah, the mappings.json file currently works like that. This list came from the unit test that is commented out of all the reports that throw `FecParserMissingMappingError`s, which isn't smart enough to know which ones could be grouped.

Plus, I get the good feeling of checking off multiple items from this list any time we fix one of those 😄

**Comment by esonderegger** [comment]
With the release of version 0.4.8, all forms listed in this issue have been mapped. All missing mappings found from here on out can probably be addressed in their own individual issue.
