### ISSUE TITLE
Missing mappings for FEC version 8.4

### ISSUE THREAD

**Issue by jason-lange** [esonderegger/fecfile#31]
**Describe the bug**
fecfile is unable to parse some independent expenditure filings since the update for version 8.4 due to missing mappings.

**To Reproduce**
import fecfile
ie_itemizations = {'filter_itemizations': ['SE','F57'], 'as_strings': True}
filing = fecfile.from_http('1616360', options=ie_itemizations)
FecParserMissingMappingError: cannot parse version 8.4 of form F5N - no mapping found

**Expected behavior**
The above code should have loaded a dictionary.

**Environment**
Python 3

**Comment by esonderegger** [comment]
Thanks for reporting this @jason-lange ! This should be fixed in version 0.7.2. Please let me know if you run into any more errors.
